### PR TITLE
Update dependencies and execution environment

### PR DESCRIPTION
**Pull request by cfsnook**
Update dependencies and upgrade execution environment to Java 1.8

### CODE REVIEW

**Review by tshoang — CHANGES_REQUESTED** [review]
I got the following related to API analysis:
- decomposition plug-in: Increase major version required (to 1.0.0)
- Decomposition Edit plug-in: Increase major version required (to 1.0.0)
- Decomposition Generator plug-in: Increase minor version required (to 0.2.0)

**Comment by cfsnook** [comment]
looks like I did not have the API baseline for decomposition. However,
I am getting major (1.0.0) required for decomposition and navigator
but minor (0.1.0) for edit and generator.
What are your baseline versions for these.. mine are 0.0.1 for all 4 plugins

**Comment by tshoang** [comment]
My baseline for decomposition:
- Decomposition: 0.0.1
- Edit: 0.0.2
- Editor: 0.1.0
- Generator: 0.0.1
This is from the CODA repository

**Comment by cfsnook** [comment]
Actually, this has never been released before so we should not do API baseline analysis at all.
We agreed to leave all plug-ins and feature as they are, at version 0.1.0. (i.e. no further changes needed).

**Review by tshoang — APPROVED** [review]

**Pull request merged**
